-- | Certificate policy: which axioms a proof may depend on.
module Gin.Certificate
  ( CertPolicy (..)
  , defaultPolicy
  , alwaysRejected
  , checkCertificate
  ) where

import Data.Containers.ListUtils (nubOrd)
import Data.Set (Set)
import Data.Set qualified as Set
import Data.Text (Text)
import Data.Text qualified as Text
import Gin.Core.Syntax (Certificate (..))
import Gin.Error (GinError, Stage (..), ginError)

-- | The axioms a certificate may name. A policy can only widen what is
-- accepted up to 'alwaysRejected', which no policy admits.
newtype CertPolicy = CertPolicy
  { allowedAxioms :: Set Text
  }
  deriving stock (Eq, Show)

-- | Lean's three standard axioms.
defaultPolicy :: CertPolicy
defaultPolicy = CertPolicy (Set.fromList ["propext", "Classical.choice", "Quot.sound"])

-- | Axioms rejected even when a caller's policy lists them: they make a
-- proof trust something other than the Lean kernel. Any axiom whose name
-- contains @._native.@ (generated by @native_decide@ and @bv_decide@) is
-- rejected as well.
alwaysRejected :: Set Text
alwaysRejected =
  Set.fromList ["sorryAx", "Lean.ofReduceBool", "Lean.ofReduceNat", "Lean.trustCompiler"]

-- | Reject an empty theorem name or statement (after trimming), any axiom
-- outside the policy in either 'certAxioms' or 'certImplAxioms', and any
-- axiom in 'alwaysRejected' or containing @._native.@. Errors use
-- 'StCertificate' and name every offending axiom.
checkCertificate :: CertPolicy -> Certificate -> Either GinError ()
checkCertificate policy c = case problems of
  [] -> Right ()
  ps -> Left (ginError StCertificate (Text.intercalate "; " ps))
  where
    problems =
      ["empty theorem name" | blank (certTheorem c)]
        <> ["empty statement" | blank (certStatement c)]
        <> axiomProblems "axioms" (certAxioms c)
        <> axiomProblems "implAxioms" (certImplAxioms c)
    blank = Text.null . Text.strip
    axiomProblems list axioms =
      [ "axiom " <> axiom <> " (in " <> list <> ") " <> reason
      | axiom <- nubOrd axioms
      , Just reason <- [verdict axiom]
      ]
    verdict axiom
      | Set.member axiom alwaysRejected = Just "is never allowed"
      | "._native." `Text.isInfixOf` axiom =
          Just "comes from native evaluation (native_decide, bv_decide) and is never allowed"
      | Set.member axiom (allowedAxioms policy) = Nothing
      | otherwise = Just "is not allowed by the axiom policy"
