-- | Certificate policy: which axioms a proof may depend on.
module Gin.Certificate
  ( CertPolicy (..)
  , defaultPolicy
  , alwaysRejected
  , checkCertificate
  ) where

import Data.Set (Set)
import Data.Set qualified as Set
import Data.Text (Text)
import Gin.Core.Syntax (Certificate)
import Gin.Error (GinError)

newtype CertPolicy = CertPolicy
  { allowedAxioms :: Set Text
  }
  deriving stock (Eq, Show)

-- | Lean's three standard axioms.
defaultPolicy :: CertPolicy
defaultPolicy = CertPolicy (Set.fromList ["propext", "Classical.choice", "Quot.sound"])

-- | Axioms rejected even when a caller's policy lists them: they make a
-- proof trust something other than the Lean kernel. Any axiom whose name
-- contains @._native.@ (generated by @native_decide@ and @bv_decide@) is
-- rejected as well.
alwaysRejected :: Set Text
alwaysRejected =
  Set.fromList ["sorryAx", "Lean.ofReduceBool", "Lean.ofReduceNat", "Lean.trustCompiler"]

-- | Reject an empty theorem name or statement (after trimming), any axiom
-- outside the policy in either 'certAxioms' or 'certImplAxioms', and any
-- axiom in 'alwaysRejected' or containing @._native.@. Errors use
-- 'StCertificate' and name every offending axiom.
checkCertificate :: CertPolicy -> Certificate -> Either GinError ()
checkCertificate = error "not yet implemented: checkCertificate"
