-- generated by gin 0.1.0.0
-- top: counter
-- theorem: Counter.counter_correct
-- statement: ∀ (en : Nat → Bool) (t : Nat),
-- statement:   Eq (Counter.counter en t) (Counter.spec en t)
-- spec: Counter.count : (Nat → Bool) → Nat → BitVec 8 :=
-- spec:   fun en t =>
-- spec:     Nat.rec (BitVec.ofNat 8 0)
-- spec:       (fun n acc => cond (en n) (HAdd.hAdd acc (BitVec.ofNat 8 1)) acc) t
-- spec: Counter.spec : (Nat → Bool) → Nat → BitVec 8 :=
-- spec:   fun en t => Counter.count en t
-- spec hash: 1b0a65b6aa47e107d2cf4e302fc3d8b6c3e3ba25b156dcf9ecbdae66026ef292
-- axioms: propext, Classical.choice, Quot.sound
-- impl axioms: propext
-- certificate: claimed by the Lean exporter, not re-checked by gin
-- validation: run gin validate with the exported vectors
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity counter is
  port (
    clk : in std_logic;
    rst : in std_logic;
    en : in std_logic;
    count : out unsigned(7 downto 0)
  );
end entity counter;

architecture gin_rtl of counter is
  signal s : unsigned(7 downto 0);
  signal s_next : unsigned(7 downto 0);
begin
  process (all)
    variable gin_v0 : unsigned(7 downto 0);
  begin
    gin_v0 := s + unsigned'("00000001");
    s_next <= gin_v0 when en = std_logic'('1') else s;
  end process;

  process (clk)
  begin
    if rising_edge(clk) then
      if rst = std_logic'('1') then
        s <= unsigned'("00000000");
      else
        s <= s_next;
      end if;
    end if;
  end process;

  count <= s;
end architecture gin_rtl;
