-- generated by gin test fixtures
-- theorem: Counter.counter_correct
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity counter is
  port (
    clk : in std_logic;
    rst : in std_logic;
    en : in std_logic;
    count : out unsigned(7 downto 0)
  );
end entity counter;

architecture gin_rtl of counter is
  signal s : unsigned(7 downto 0);
  signal s_next : unsigned(7 downto 0);
begin
  process (all)
    variable gin_v_inc : unsigned(7 downto 0);
    variable gin_v_s_next : unsigned(7 downto 0);
  begin
    gin_v_inc := s + unsigned'("00000001");
    gin_v_s_next := gin_v_inc when en = std_logic'('1') else s;
    s_next <= gin_v_s_next;
  end process;

  process (clk)
  begin
    if rising_edge(clk) then
      if rst = std_logic'('1') then
        s <= unsigned'("00000000");
      else
        s <= s_next;
      end if;
    end if;
  end process;

  count <= s;
end architecture gin_rtl;
