-- generated by gin test fixtures
-- theorem: Counter.counter_correct
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity counter_tb is
end entity counter_tb;

architecture gin_tb of counter_tb is
  type gin_row is record
    en : std_logic;
    count : unsigned(7 downto 0);
  end record gin_row;
  type gin_rows is array (natural range <>) of gin_row;
  constant gin_vectors : gin_rows(0 to 7) := (
    0 => (en => '1', count => 8x"00"),
    1 => (en => '1', count => 8x"01"),
    2 => (en => '0', count => 8x"02"),
    3 => (en => '1', count => 8x"02"),
    4 => (en => '0', count => 8x"03"),
    5 => (en => '0', count => 8x"03"),
    6 => (en => '1', count => 8x"03"),
    7 => (en => '1', count => 8x"04")
  );

  signal gin_sig_clk : std_logic := '0';
  signal gin_sig_rst : std_logic := '1';
  signal gin_sig_en : std_logic := '0';
  signal gin_sig_count : unsigned(7 downto 0);
begin
  gin_dut : entity work.counter
    port map (
      clk => gin_sig_clk,
      rst => gin_sig_rst,
      en => gin_sig_en,
      count => gin_sig_count
    );

  gin_stimulus : process
    variable gin_line : line;
    variable gin_mismatches : natural := 0;
  begin
    -- Reset: clock low, reset high, every input zero; one rising edge
    -- loads the registers' initial values, then reset is released.
    gin_sig_clk <= '0';
    gin_sig_rst <= '1';
    gin_sig_en <= '0';
    wait for 5 ns;
    gin_sig_clk <= '1';
    wait for 5 ns;
    gin_sig_clk <= '0';
    gin_sig_rst <= '0';
    -- Each cycle: drive the inputs with the clock low, compare every
    -- output 1 ns later, then one rising edge.
    for gin_t in 0 to 7 loop
      gin_sig_en <= gin_vectors(gin_t).en;
      wait for 1 ns;
      if gin_sig_count /= gin_vectors(gin_t).count then
        gin_mismatches := gin_mismatches + 1;
        write(gin_line, string'("GIN-MISMATCH cycle="));
        write(gin_line, gin_t);
        write(gin_line, string'(" port=count expected="));
        write(gin_line, to_hstring(gin_vectors(gin_t).count));
        write(gin_line, string'(" got="));
        write(gin_line, to_hstring(gin_sig_count));
        writeline(output, gin_line);
      end if;
      wait for 4 ns;
      gin_sig_clk <= '1';
      wait for 5 ns;
      gin_sig_clk <= '0';
    end loop;
    if gin_mismatches = 0 then
      write(gin_line, string'("GIN-PASS cycles=8"));
    else
      write(gin_line, string'("GIN-FAIL mismatches="));
      write(gin_line, gin_mismatches);
    end if;
    writeline(output, gin_line);
    std.env.finish;
    wait;
  end process gin_stimulus;
end architecture gin_tb;
