-- generated by gin test fixtures
-- theorem: Detector.detector_correct
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity detector is
  port (
    clk : in std_logic;
    rst : in std_logic;
    b : in std_logic;
    hit : out std_logic
  );
end entity detector;

architecture gin_rtl of detector is
  signal s : unsigned(1 downto 0);
  signal s_next : unsigned(1 downto 0);
  signal o_hit : std_logic;
begin
  process (all)
    variable gin_v_is0 : std_logic;
    variable gin_v_is1 : std_logic;
    variable gin_v_pick10 : unsigned(1 downto 0);
    variable gin_v_pick12 : unsigned(1 downto 0);
    variable gin_v_s_inner : unsigned(1 downto 0);
    variable gin_v_s_next : unsigned(1 downto 0);
    variable gin_v_hit_inner : std_logic;
    variable gin_v_o_hit : std_logic;
  begin
    gin_v_is0 := std_logic'('1') when s = unsigned'("00") else std_logic'('0');
    gin_v_is1 := std_logic'('1') when s = unsigned'("01") else std_logic'('0');
    gin_v_pick10 := unsigned'("01") when b = std_logic'('1') else unsigned'("00");
    gin_v_pick12 := unsigned'("01") when b = std_logic'('1') else unsigned'("10");
    gin_v_s_inner := gin_v_pick12 when gin_v_is1 = std_logic'('1') else gin_v_pick10;
    gin_v_s_next := gin_v_pick10 when gin_v_is0 = std_logic'('1') else gin_v_s_inner;
    gin_v_hit_inner := std_logic'('0') when gin_v_is1 = std_logic'('1') else b;
    gin_v_o_hit := std_logic'('0') when gin_v_is0 = std_logic'('1') else gin_v_hit_inner;
    s_next <= gin_v_s_next;
    o_hit <= gin_v_o_hit;
  end process;

  process (clk)
  begin
    if rising_edge(clk) then
      if rst = std_logic'('1') then
        s <= unsigned'("00");
      else
        s <= s_next;
      end if;
    end if;
  end process;

  hit <= o_hit;
end architecture gin_rtl;
