-- generated by gin test fixtures
-- theorem: Detector.detector_correct
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity detector_tb is
end entity detector_tb;

architecture gin_tb of detector_tb is
  type gin_row is record
    b : std_logic;
    hit : std_logic;
  end record gin_row;
  type gin_rows is array (natural range <>) of gin_row;
  constant gin_vectors : gin_rows(0 to 7) := (
    0 => (b => '1', hit => '0'),
    1 => (b => '0', hit => '0'),
    2 => (b => '1', hit => '1'),
    3 => (b => '0', hit => '0'),
    4 => (b => '1', hit => '1'),
    5 => (b => '1', hit => '0'),
    6 => (b => '0', hit => '0'),
    7 => (b => '1', hit => '1')
  );

  signal gin_sig_clk : std_logic := '0';
  signal gin_sig_rst : std_logic := '1';
  signal gin_sig_b : std_logic := '0';
  signal gin_sig_hit : std_logic;
begin
  gin_dut : entity work.detector
    port map (
      clk => gin_sig_clk,
      rst => gin_sig_rst,
      b => gin_sig_b,
      hit => gin_sig_hit
    );

  gin_stimulus : process
    variable gin_line : line;
    variable gin_mismatches : natural := 0;
  begin
    -- Reset: clock low, reset high, every input zero; one rising edge
    -- loads the registers' initial values, then reset is released.
    gin_sig_clk <= '0';
    gin_sig_rst <= '1';
    gin_sig_b <= '0';
    wait for 5 ns;
    gin_sig_clk <= '1';
    wait for 5 ns;
    gin_sig_clk <= '0';
    gin_sig_rst <= '0';
    -- Each cycle: drive the inputs with the clock low, compare every
    -- output 1 ns later, then one rising edge.
    for gin_t in 0 to 7 loop
      gin_sig_b <= gin_vectors(gin_t).b;
      wait for 1 ns;
      if gin_sig_hit /= gin_vectors(gin_t).hit then
        gin_mismatches := gin_mismatches + 1;
        write(gin_line, string'("GIN-MISMATCH cycle="));
        write(gin_line, gin_t);
        write(gin_line, string'(" port=hit expected="));
        write(gin_line, to_string(gin_vectors(gin_t).hit));
        write(gin_line, string'(" got="));
        write(gin_line, to_string(gin_sig_hit));
        writeline(output, gin_line);
      end if;
      wait for 4 ns;
      gin_sig_clk <= '1';
      wait for 5 ns;
      gin_sig_clk <= '0';
    end loop;
    if gin_mismatches = 0 then
      write(gin_line, string'("GIN-PASS cycles=8"));
    else
      write(gin_line, string'("GIN-FAIL mismatches="));
      write(gin_line, gin_mismatches);
    end if;
    writeline(output, gin_line);
    std.env.finish;
    wait;
  end process gin_stimulus;
end architecture gin_tb;
