-- generated by gin test fixtures
-- theorem: Detector.detector_correct
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity detector is
  port (
    clk : in std_logic;
    rst : in std_logic;
    b : in std_logic;
    hit : out std_logic
  );
end entity detector;

architecture gin_rtl of detector is
  signal s : unsigned(1 downto 0);
  signal is0 : std_logic;
  signal is1 : std_logic;
  signal pick10 : unsigned(1 downto 0);
  signal pick12 : unsigned(1 downto 0);
  signal s_inner : unsigned(1 downto 0);
  signal s_next : unsigned(1 downto 0);
  signal hit_inner : std_logic;
  signal o_hit : std_logic;
begin
  is0 <= std_logic'('1') when s = unsigned'("00") else std_logic'('0');
  is1 <= std_logic'('1') when s = unsigned'("01") else std_logic'('0');
  pick10 <= unsigned'("01") when b = std_logic'('1') else unsigned'("00");
  pick12 <= unsigned'("01") when b = std_logic'('1') else unsigned'("10");
  s_inner <= pick12 when is1 = std_logic'('1') else pick10;
  s_next <= pick10 when is0 = std_logic'('1') else s_inner;
  hit_inner <= std_logic'('0') when is1 = std_logic'('1') else b;
  o_hit <= std_logic'('0') when is0 = std_logic'('1') else hit_inner;

  process (clk)
  begin
    if rising_edge(clk) then
      if rst = std_logic'('1') then
        s <= unsigned'("00");
      else
        s <= s_next;
      end if;
    end if;
  end process;

  hit <= o_hit;
end architecture gin_rtl;
