-- generated by gin test fixtures
-- theorem: Mac.mac_correct
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity mac is
  port (
    clk : in std_logic;
    rst : in std_logic;
    x : in unsigned(7 downto 0);
    y : in unsigned(7 downto 0);
    acc : out unsigned(15 downto 0)
  );
end entity mac;

architecture gin_rtl of mac is
  signal acc_q : unsigned(15 downto 0);
  signal sum : unsigned(15 downto 0);
begin
  process (all)
    variable gin_v0 : unsigned(15 downto 0);
    variable gin_v1 : unsigned(15 downto 0);
    variable gin_v2 : unsigned(15 downto 0);
  begin
    gin_v0 := resize(x, 16);
    gin_v1 := resize(y, 16);
    gin_v2 := resize(gin_v0 * gin_v1, 16);
    sum <= acc_q + gin_v2;
  end process;

  process (clk)
  begin
    if rising_edge(clk) then
      if rst = std_logic'('1') then
        acc_q <= unsigned'("0000000000000000");
      else
        acc_q <= sum;
      end if;
    end if;
  end process;

  acc <= acc_q;
end architecture gin_rtl;
