-- generated by gin test fixtures
-- theorem: Mac.mac_correct
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity mac_tb is
end entity mac_tb;

architecture gin_tb of mac_tb is
  type gin_row is record
    x : unsigned(7 downto 0);
    y : unsigned(7 downto 0);
    acc : unsigned(15 downto 0);
  end record gin_row;
  type gin_rows is array (natural range <>) of gin_row;
  constant gin_vectors : gin_rows(0 to 4) := (
    0 => (x => 8x"03", y => 8x"04", acc => 16x"0000"),
    1 => (x => 8x"05", y => 8x"06", acc => 16x"000C"),
    2 => (x => 8x"FF", y => 8x"FF", acc => 16x"002A"),
    3 => (x => 8x"FF", y => 8x"FF", acc => 16x"FE2B"),
    4 => (x => 8x"00", y => 8x"00", acc => 16x"FC2C")
  );

  signal gin_sig_clk : std_logic := '0';
  signal gin_sig_rst : std_logic := '1';
  signal gin_sig_x : unsigned(7 downto 0) := (others => '0');
  signal gin_sig_y : unsigned(7 downto 0) := (others => '0');
  signal gin_sig_acc : unsigned(15 downto 0);
begin
  gin_dut : entity work.mac
    port map (
      clk => gin_sig_clk,
      rst => gin_sig_rst,
      x => gin_sig_x,
      y => gin_sig_y,
      acc => gin_sig_acc
    );

  gin_stimulus : process
    variable gin_line : line;
    variable gin_mismatches : natural := 0;
  begin
    -- Reset: clock low, reset high, every input zero; one rising edge
    -- loads the registers' initial values, then reset is released.
    gin_sig_clk <= '0';
    gin_sig_rst <= '1';
    gin_sig_x <= (others => '0');
    gin_sig_y <= (others => '0');
    wait for 5 ns;
    gin_sig_clk <= '1';
    wait for 5 ns;
    gin_sig_clk <= '0';
    gin_sig_rst <= '0';
    -- Each cycle: drive the inputs with the clock low, compare every
    -- output 1 ns later, then one rising edge.
    for gin_t in 0 to 4 loop
      gin_sig_x <= gin_vectors(gin_t).x;
      gin_sig_y <= gin_vectors(gin_t).y;
      wait for 1 ns;
      if gin_sig_acc /= gin_vectors(gin_t).acc then
        gin_mismatches := gin_mismatches + 1;
        write(gin_line, string'("GIN-MISMATCH cycle="));
        write(gin_line, gin_t);
        write(gin_line, string'(" port=acc expected="));
        write(gin_line, to_hstring(gin_vectors(gin_t).acc));
        write(gin_line, string'(" got="));
        write(gin_line, to_hstring(gin_sig_acc));
        writeline(output, gin_line);
      end if;
      wait for 4 ns;
      gin_sig_clk <= '1';
      wait for 5 ns;
      gin_sig_clk <= '0';
    end loop;
    if gin_mismatches = 0 then
      write(gin_line, string'("GIN-PASS cycles=5"));
    else
      write(gin_line, string'("GIN-FAIL mismatches="));
      write(gin_line, gin_mismatches);
    end if;
    writeline(output, gin_line);
    std.env.finish;
    wait;
  end process gin_stimulus;
end architecture gin_tb;
