// generated by the backend test suite
module comb (
  /* verilator lint_off UNUSEDSIGNAL */
  input wire clk,
  /* verilator lint_on UNUSEDSIGNAL */
  /* verilator lint_off UNUSEDSIGNAL */
  input wire rst,
  /* verilator lint_on UNUSEDSIGNAL */
  input wire [3:0] a,
  output wire [3:0] y
);

  wire [3:0] na;

  assign na = ~a;

  assign y = na;
endmodule
