// generated by gin test fixtures
// theorem: Counter.counter_correct
module counter (
  input wire clk,
  input wire rst,
  input wire en,
  output wire [7:0] count
);

  reg [7:0] s;
  wire [7:0] inc;
  wire [7:0] s_next;

  always @(posedge clk) begin
    if (rst) begin
      s <= 8'h00;
    end else begin
      s <= s_next;
    end
  end
  assign inc = s + 8'h01;
  assign s_next = en ? inc : s;

  assign count = s;
endmodule
