// generated by gin test fixtures
// theorem: Counter.counter_correct
`timescale 1ns/1ps

module counter_tb;
  reg clk;
  reg rst;
  reg en;
  wire [7:0] count;
  integer gin_mismatches;

  counter gin_dut (
    .clk(clk),
    .rst(rst),
    .en(en),
    .count(count)
  );

  initial begin
    gin_mismatches = 0;
    clk = 1'b0;
    rst = 1'b1;
    en = 1'b0;
    #5 clk = 1'b1;
    #5 clk = 1'b0;
    rst = 1'b0;
    // cycle 0
    en = 1'b1;
    #1;
    if (count !== 8'h00) begin
      $display("GIN-MISMATCH cycle=0 port=count expected=00 got=%h", count);
      gin_mismatches = gin_mismatches + 1;
    end
    #4 clk = 1'b1;
    #5 clk = 1'b0;
    // cycle 1
    en = 1'b1;
    #1;
    if (count !== 8'h01) begin
      $display("GIN-MISMATCH cycle=1 port=count expected=01 got=%h", count);
      gin_mismatches = gin_mismatches + 1;
    end
    #4 clk = 1'b1;
    #5 clk = 1'b0;
    // cycle 2
    en = 1'b0;
    #1;
    if (count !== 8'h02) begin
      $display("GIN-MISMATCH cycle=2 port=count expected=02 got=%h", count);
      gin_mismatches = gin_mismatches + 1;
    end
    #4 clk = 1'b1;
    #5 clk = 1'b0;
    // cycle 3
    en = 1'b1;
    #1;
    if (count !== 8'h02) begin
      $display("GIN-MISMATCH cycle=3 port=count expected=02 got=%h", count);
      gin_mismatches = gin_mismatches + 1;
    end
    #4 clk = 1'b1;
    #5 clk = 1'b0;
    // cycle 4
    en = 1'b0;
    #1;
    if (count !== 8'h03) begin
      $display("GIN-MISMATCH cycle=4 port=count expected=03 got=%h", count);
      gin_mismatches = gin_mismatches + 1;
    end
    #4 clk = 1'b1;
    #5 clk = 1'b0;
    // cycle 5
    en = 1'b0;
    #1;
    if (count !== 8'h03) begin
      $display("GIN-MISMATCH cycle=5 port=count expected=03 got=%h", count);
      gin_mismatches = gin_mismatches + 1;
    end
    #4 clk = 1'b1;
    #5 clk = 1'b0;
    // cycle 6
    en = 1'b1;
    #1;
    if (count !== 8'h03) begin
      $display("GIN-MISMATCH cycle=6 port=count expected=03 got=%h", count);
      gin_mismatches = gin_mismatches + 1;
    end
    #4 clk = 1'b1;
    #5 clk = 1'b0;
    // cycle 7
    en = 1'b1;
    #1;
    if (count !== 8'h04) begin
      $display("GIN-MISMATCH cycle=7 port=count expected=04 got=%h", count);
      gin_mismatches = gin_mismatches + 1;
    end
    #4 clk = 1'b1;
    #5 clk = 1'b0;
    if (gin_mismatches == 0) begin
      $display("GIN-PASS cycles=8");
    end else begin
      $display("GIN-FAIL mismatches=%0d", gin_mismatches);
    end
    $finish;
  end
endmodule
