// generated by gin test fixtures
// theorem: Detector.detector_correct
`timescale 1ns/1ps

module detector_tb;
  reg clk;
  reg rst;
  reg b;
  wire hit;
  integer gin_mismatches;

  detector gin_dut (
    .clk(clk),
    .rst(rst),
    .b(b),
    .hit(hit)
  );

  initial begin
    gin_mismatches = 0;
    clk = 1'b0;
    rst = 1'b1;
    b = 1'b0;
    #5 clk = 1'b1;
    #5 clk = 1'b0;
    rst = 1'b0;
    // cycle 0
    b = 1'b1;
    #1;
    if (hit !== 1'b0) begin
      $display("GIN-MISMATCH cycle=0 port=hit expected=0 got=%h", hit);
      gin_mismatches = gin_mismatches + 1;
    end
    #4 clk = 1'b1;
    #5 clk = 1'b0;
    // cycle 1
    b = 1'b0;
    #1;
    if (hit !== 1'b0) begin
      $display("GIN-MISMATCH cycle=1 port=hit expected=0 got=%h", hit);
      gin_mismatches = gin_mismatches + 1;
    end
    #4 clk = 1'b1;
    #5 clk = 1'b0;
    // cycle 2
    b = 1'b1;
    #1;
    if (hit !== 1'b1) begin
      $display("GIN-MISMATCH cycle=2 port=hit expected=1 got=%h", hit);
      gin_mismatches = gin_mismatches + 1;
    end
    #4 clk = 1'b1;
    #5 clk = 1'b0;
    // cycle 3
    b = 1'b0;
    #1;
    if (hit !== 1'b0) begin
      $display("GIN-MISMATCH cycle=3 port=hit expected=0 got=%h", hit);
      gin_mismatches = gin_mismatches + 1;
    end
    #4 clk = 1'b1;
    #5 clk = 1'b0;
    // cycle 4
    b = 1'b1;
    #1;
    if (hit !== 1'b1) begin
      $display("GIN-MISMATCH cycle=4 port=hit expected=1 got=%h", hit);
      gin_mismatches = gin_mismatches + 1;
    end
    #4 clk = 1'b1;
    #5 clk = 1'b0;
    // cycle 5
    b = 1'b1;
    #1;
    if (hit !== 1'b0) begin
      $display("GIN-MISMATCH cycle=5 port=hit expected=0 got=%h", hit);
      gin_mismatches = gin_mismatches + 1;
    end
    #4 clk = 1'b1;
    #5 clk = 1'b0;
    // cycle 6
    b = 1'b0;
    #1;
    if (hit !== 1'b0) begin
      $display("GIN-MISMATCH cycle=6 port=hit expected=0 got=%h", hit);
      gin_mismatches = gin_mismatches + 1;
    end
    #4 clk = 1'b1;
    #5 clk = 1'b0;
    // cycle 7
    b = 1'b1;
    #1;
    if (hit !== 1'b1) begin
      $display("GIN-MISMATCH cycle=7 port=hit expected=1 got=%h", hit);
      gin_mismatches = gin_mismatches + 1;
    end
    #4 clk = 1'b1;
    #5 clk = 1'b0;
    if (gin_mismatches == 0) begin
      $display("GIN-PASS cycles=8");
    end else begin
      $display("GIN-FAIL mismatches=%0d", gin_mismatches);
    end
    $finish;
  end
endmodule
