// generated by gin test fixtures
// theorem: Mac.mac_correct
module mac (
  input wire clk,
  input wire rst,
  input wire [7:0] x,
  input wire [7:0] y,
  output wire [15:0] acc
);

  reg [15:0] acc_q;
  wire [15:0] xz;
  wire [15:0] yz;
  wire [15:0] prod;
  wire [15:0] sum;

  always @(posedge clk) begin
    if (rst) begin
      acc_q <= 16'h0000;
    end else begin
      acc_q <= sum;
    end
  end
  assign xz = {{8{1'b0}}, x};
  assign yz = {{8{1'b0}}, y};
  assign prod = xz * yz;
  assign sum = acc_q + prod;

  assign acc = acc_q;
endmodule
