// generated by gin test fixtures
// theorem: Mac.mac_correct
`timescale 1ns/1ps

module mac_tb;
  reg clk;
  reg rst;
  reg [7:0] x;
  reg [7:0] y;
  wire [15:0] acc;
  integer gin_mismatches;

  mac gin_dut (
    .clk(clk),
    .rst(rst),
    .x(x),
    .y(y),
    .acc(acc)
  );

  initial begin
    gin_mismatches = 0;
    clk = 1'b0;
    rst = 1'b1;
    x = 8'h00;
    y = 8'h00;
    #5 clk = 1'b1;
    #5 clk = 1'b0;
    rst = 1'b0;
    // cycle 0
    x = 8'h03;
    y = 8'h04;
    #1;
    if (acc !== 16'h0000) begin
      $display("GIN-MISMATCH cycle=0 port=acc expected=0000 got=%h", acc);
      gin_mismatches = gin_mismatches + 1;
    end
    #4 clk = 1'b1;
    #5 clk = 1'b0;
    // cycle 1
    x = 8'h05;
    y = 8'h06;
    #1;
    if (acc !== 16'h000c) begin
      $display("GIN-MISMATCH cycle=1 port=acc expected=000c got=%h", acc);
      gin_mismatches = gin_mismatches + 1;
    end
    #4 clk = 1'b1;
    #5 clk = 1'b0;
    // cycle 2
    x = 8'hff;
    y = 8'hff;
    #1;
    if (acc !== 16'h002a) begin
      $display("GIN-MISMATCH cycle=2 port=acc expected=002a got=%h", acc);
      gin_mismatches = gin_mismatches + 1;
    end
    #4 clk = 1'b1;
    #5 clk = 1'b0;
    // cycle 3
    x = 8'hff;
    y = 8'hff;
    #1;
    if (acc !== 16'hfe2b) begin
      $display("GIN-MISMATCH cycle=3 port=acc expected=fe2b got=%h", acc);
      gin_mismatches = gin_mismatches + 1;
    end
    #4 clk = 1'b1;
    #5 clk = 1'b0;
    // cycle 4
    x = 8'h00;
    y = 8'h00;
    #1;
    if (acc !== 16'hfc2c) begin
      $display("GIN-MISMATCH cycle=4 port=acc expected=fc2c got=%h", acc);
      gin_mismatches = gin_mismatches + 1;
    end
    #4 clk = 1'b1;
    #5 clk = 1'b0;
    if (gin_mismatches == 0) begin
      $display("GIN-PASS cycles=5");
    end else begin
      $display("GIN-FAIL mismatches=%0d", gin_mismatches);
    end
    $finish;
  end
endmodule
