// generated by the backend test suite
module spare (
  input wire clk,
  input wire rst,
  input wire [7:0] a,
  /* verilator lint_off UNUSEDSIGNAL */
  input wire b,
  /* verilator lint_on UNUSEDSIGNAL */
  /* verilator lint_off UNUSEDSIGNAL */
  input wire [7:0] c,
  /* verilator lint_on UNUSEDSIGNAL */
  input wire [7:0] d,
  output wire [3:0] o_c,
  output wire [3:0] o_dh,
  output wire [3:0] o_dl,
  output wire [0:0] o_m
);

  wire [3:0] c_lo;
  wire [3:0] d_hi;
  wire [3:0] d_lo;
  reg [7:0] q;
  /* verilator lint_off UNUSEDSIGNAL */
  wire [7:0] t;
  /* verilator lint_on UNUSEDSIGNAL */
  wire [0:0] t_msb;

  assign c_lo = c[3:0];
  assign d_hi = d[7:4];
  assign d_lo = d[3:0];
  always @(posedge clk) begin
    if (rst) begin
      q <= 8'h00;
    end else begin
      q <= a;
    end
  end
  assign t = q ^ a;
  assign t_msb = t[7:7];

  assign o_c = c_lo;
  assign o_dh = d_hi;
  assign o_dl = d_lo;
  assign o_m = t_msb;
endmodule
