// generated by the backend test suite
module allops (
  input logic clk,
  input logic rst,
  input logic [7:0] a,
  input logic [7:0] b,
  input logic p,
  input logic q,
  output logic [7:0] o_acc,
  output logic [7:0] o_acc_next,
  output logic [2:0] o_acc_hi,
  output logic o_flag,
  output logic [3:0] o_held,
  output logic [7:0] o_n0,
  output logic [7:0] o_n1,
  output logic o_n2,
  output logic [7:0] o_n3,
  output logic [7:0] o_n4,
  output logic o_n5,
  output logic o_n6,
  output logic [7:0] o_n7,
  output logic [7:0] o_n8,
  output logic [7:0] o_n9,
  output logic [7:0] o_n10,
  output logic [7:0] o_n11,
  output logic [7:0] o_n12,
  output logic [7:0] o_n13,
  output logic [7:0] o_n14,
  output logic [7:0] o_n15,
  output logic [7:0] o_n16,
  output logic [7:0] o_n17,
  output logic [7:0] o_n18,
  output logic [7:0] o_n19,
  output logic [7:0] o_n20,
  output logic [7:0] o_n21,
  output logic [7:0] o_n22,
  output logic [7:0] o_n23,
  output logic [7:0] o_n24,
  output logic [7:0] o_n25,
  output logic [7:0] o_n26,
  output logic o_n27,
  output logic o_n28,
  output logic o_n29,
  output logic o_n30,
  output logic o_n31,
  output logic o_n32,
  output logic o_n33,
  output logic o_n34,
  output logic o_n35,
  output logic o_n36,
  output logic o_n37,
  output logic o_n38,
  output logic o_n39,
  output logic o_n40,
  output logic o_n41,
  output logic o_n42,
  output logic o_n43,
  output logic o_n44,
  output logic o_n45,
  output logic o_n46,
  output logic o_n47,
  output logic [7:0] o_n48,
  output logic [7:0] o_n49,
  output logic [7:0] o_n50,
  output logic [7:0] o_n51,
  output logic o_n52,
  output logic [7:0] o_n53,
  output logic [7:0] o_n54,
  output logic [7:0] o_n55,
  output logic [7:0] o_n56,
  output logic [7:0] o_n57,
  output logic [7:0] o_n58,
  output logic [7:0] o_n59,
  output logic [7:0] o_n60,
  output logic [3:0] o_n61,
  output logic [0:0] o_n62,
  output logic [7:0] o_n63,
  output logic [15:0] o_n64,
  output logic [11:0] o_n65,
  output logic [8:0] o_n66,
  output logic [15:0] o_n67,
  output logic [7:0] o_n68,
  output logic [11:0] o_n69,
  output logic [0:0] o_n70,
  output logic [0:0] o_n71,
  output logic [7:0] o_k8,
  output logic o_kb,
  output logic o_q
);

  logic [7:0] acc;
  logic [7:0] acc_next;
  logic [2:0] acc_hi;
  logic flag;
  logic [3:0] held;
  logic [7:0] n0;
  logic [7:0] n1;
  logic n2;
  logic [7:0] n3;
  logic [7:0] n4;
  logic n5;
  logic n6;
  logic [7:0] n7;
  logic [7:0] n8;
  logic [7:0] n9;
  logic [7:0] n10;
  logic [7:0] n11;
  logic [7:0] n12;
  logic [7:0] n13;
  logic [7:0] n14;
  logic [7:0] n15;
  logic [7:0] n16;
  logic [7:0] n17;
  logic [7:0] n18;
  logic [7:0] n19;
  logic [7:0] n20;
  logic [7:0] n21;
  logic [7:0] n22;
  logic [7:0] n23;
  logic [7:0] n24;
  logic [7:0] n25;
  logic [7:0] n26;
  logic n27;
  logic n28;
  logic n29;
  logic n30;
  logic n31;
  logic n32;
  logic n33;
  logic n34;
  logic n35;
  logic n36;
  logic n37;
  logic n38;
  logic n39;
  logic n40;
  logic n41;
  logic n42;
  logic n43;
  logic n44;
  logic n45;
  logic n46;
  logic n47;
  logic [7:0] n48;
  logic [7:0] n49;
  logic [7:0] n50;
  logic [7:0] n51;
  logic n52;
  logic [7:0] n53;
  logic [7:0] n54;
  logic [7:0] n55;
  logic [7:0] n56;
  logic [7:0] n57;
  logic [7:0] n58;
  logic [7:0] n59;
  logic [7:0] n60;
  logic [3:0] n61;
  logic [0:0] n62;
  logic [7:0] n63;
  logic [15:0] n64;
  logic [11:0] n65;
  logic [8:0] n66;
  logic [15:0] n67;
  logic [7:0] n68;
  logic [11:0] n69;
  logic [0:0] n70;
  logic [0:0] n71;

  always_ff @(posedge clk) begin
    if (rst) begin
      acc <= 8'ha5;
    end else begin
      acc <= acc_next;
    end
  end
  assign acc_next = acc + a;
  assign acc_hi = acc[7:5];
  always_ff @(posedge clk) begin
    if (rst) begin
      flag <= 1'b1;
    end else begin
      flag <= p;
    end
  end
  always_ff @(posedge clk) begin
    if (rst) begin
      held <= 4'h3;
    end else begin
      held <= 4'h9;
    end
  end
  assign n0 = a;
  assign n1 = 8'h5a;
  assign n2 = 1'b1;
  assign n3 = ~a;
  assign n4 = ~8'h0f;
  assign n5 = ~p;
  assign n6 = ~1'b0;
  assign n7 = -a;
  assign n8 = -8'h01;
  assign n9 = a & b;
  assign n10 = 8'hc3 & b;
  assign n11 = a & 8'h3c;
  assign n12 = a | b;
  assign n13 = 8'hc3 | b;
  assign n14 = a | 8'h3c;
  assign n15 = a ^ b;
  assign n16 = 8'hc3 ^ b;
  assign n17 = a ^ 8'h3c;
  assign n18 = a + b;
  assign n19 = 8'hc3 + b;
  assign n20 = a + 8'h3c;
  assign n21 = a - b;
  assign n22 = 8'hc3 - b;
  assign n23 = a - 8'h3c;
  assign n24 = a * b;
  assign n25 = 8'hc3 * b;
  assign n26 = a * 8'h3c;
  assign n27 = a == b;
  assign n28 = 8'hc3 == b;
  assign n29 = a == 8'h3c;
  assign n30 = a < b;
  assign n31 = 8'hc3 < b;
  assign n32 = a < 8'h3c;
  assign n33 = a <= b;
  assign n34 = 8'hc3 <= b;
  assign n35 = a <= 8'h3c;
  assign n36 = p & q;
  assign n37 = 1'b1 & q;
  assign n38 = p & 1'b0;
  assign n39 = p | q;
  assign n40 = 1'b1 | q;
  assign n41 = p | 1'b0;
  assign n42 = p ^ q;
  assign n43 = 1'b1 ^ q;
  assign n44 = p ^ 1'b0;
  assign n45 = p == q;
  assign n46 = 1'b1 == q;
  assign n47 = p == 1'b0;
  assign n48 = p ? a : b;
  assign n49 = 1'b1 ? a : b;
  assign n50 = p ? 8'h11 : b;
  assign n51 = p ? a : 8'h22;
  assign n52 = q ? p : 1'b1;
  assign n53 = a << 1'h0;
  assign n54 = a << 2'h3;
  assign n55 = a << 3'h7;
  assign n56 = 8'h81 << 2'h2;
  assign n57 = a >> 1'h0;
  assign n58 = a >> 2'h3;
  assign n59 = a >> 3'h7;
  assign n60 = 8'hf0 >> 3'h5;
  assign n61 = a[7:4];
  assign n62 = b[0:0];
  assign n63 = a[7:0];
  assign n64 = {a, b};
  assign n65 = {4'ha, b};
  assign n66 = {a, 1'h1};
  assign n67 = {{8{1'b0}}, a};
  assign n68 = b;
  assign n69 = {{4{1'b0}}, 8'hff};
  assign n70 = p;
  assign n71 = 1'b1;

  assign o_acc = acc;
  assign o_acc_next = acc_next;
  assign o_acc_hi = acc_hi;
  assign o_flag = flag;
  assign o_held = held;
  assign o_n0 = n0;
  assign o_n1 = n1;
  assign o_n2 = n2;
  assign o_n3 = n3;
  assign o_n4 = n4;
  assign o_n5 = n5;
  assign o_n6 = n6;
  assign o_n7 = n7;
  assign o_n8 = n8;
  assign o_n9 = n9;
  assign o_n10 = n10;
  assign o_n11 = n11;
  assign o_n12 = n12;
  assign o_n13 = n13;
  assign o_n14 = n14;
  assign o_n15 = n15;
  assign o_n16 = n16;
  assign o_n17 = n17;
  assign o_n18 = n18;
  assign o_n19 = n19;
  assign o_n20 = n20;
  assign o_n21 = n21;
  assign o_n22 = n22;
  assign o_n23 = n23;
  assign o_n24 = n24;
  assign o_n25 = n25;
  assign o_n26 = n26;
  assign o_n27 = n27;
  assign o_n28 = n28;
  assign o_n29 = n29;
  assign o_n30 = n30;
  assign o_n31 = n31;
  assign o_n32 = n32;
  assign o_n33 = n33;
  assign o_n34 = n34;
  assign o_n35 = n35;
  assign o_n36 = n36;
  assign o_n37 = n37;
  assign o_n38 = n38;
  assign o_n39 = n39;
  assign o_n40 = n40;
  assign o_n41 = n41;
  assign o_n42 = n42;
  assign o_n43 = n43;
  assign o_n44 = n44;
  assign o_n45 = n45;
  assign o_n46 = n46;
  assign o_n47 = n47;
  assign o_n48 = n48;
  assign o_n49 = n49;
  assign o_n50 = n50;
  assign o_n51 = n51;
  assign o_n52 = n52;
  assign o_n53 = n53;
  assign o_n54 = n54;
  assign o_n55 = n55;
  assign o_n56 = n56;
  assign o_n57 = n57;
  assign o_n58 = n58;
  assign o_n59 = n59;
  assign o_n60 = n60;
  assign o_n61 = n61;
  assign o_n62 = n62;
  assign o_n63 = n63;
  assign o_n64 = n64;
  assign o_n65 = n65;
  assign o_n66 = n66;
  assign o_n67 = n67;
  assign o_n68 = n68;
  assign o_n69 = n69;
  assign o_n70 = n70;
  assign o_n71 = n71;
  assign o_k8 = 8'h3c;
  assign o_kb = 1'b0;
  assign o_q = q;
endmodule
