// generated by the backend test suite
module comb (
  /* verilator lint_off UNUSEDSIGNAL */
  input logic clk,
  /* verilator lint_on UNUSEDSIGNAL */
  /* verilator lint_off UNUSEDSIGNAL */
  input logic rst,
  /* verilator lint_on UNUSEDSIGNAL */
  input logic [3:0] a,
  output logic [3:0] y
);

  logic [3:0] na;

  assign na = ~a;

  assign y = na;
endmodule
