// generated by gin 0.1.0.0
// top: counter
// theorem: Counter.counter_correct
// statement: ∀ (en : Nat → Bool) (t : Nat),
// statement:   Eq (Counter.counter en t) (Counter.spec en t)
// spec: Counter.count : (Nat → Bool) → Nat → BitVec 8 :=
// spec:   fun en t =>
// spec:     Nat.rec (BitVec.ofNat 8 0)
// spec:       (fun n acc => cond (en n) (HAdd.hAdd acc (BitVec.ofNat 8 1)) acc) t
// spec: Counter.spec : (Nat → Bool) → Nat → BitVec 8 :=
// spec:   fun en t => Counter.count en t
// spec hash: 1b0a65b6aa47e107d2cf4e302fc3d8b6c3e3ba25b156dcf9ecbdae66026ef292
// axioms: propext, Classical.choice, Quot.sound
// impl axioms: propext
// certificate: claimed by the Lean exporter, not re-checked by gin
// validation: run gin validate with the exported vectors
module counter (
  input logic clk,
  input logic rst,
  input logic en,
  output logic [7:0] count
);

  logic [7:0] s;
  logic [7:0] inc;
  logic [7:0] s_next;

  always_ff @(posedge clk) begin
    if (rst) begin
      s <= 8'h00;
    end else begin
      s <= s_next;
    end
  end
  assign inc = s + 8'h01;
  assign s_next = en ? inc : s;

  assign count = s;
endmodule
