// generated by gin test fixtures
// theorem: Counter.counter_correct
module counter (
  input logic clk,
  input logic rst,
  input logic en,
  output logic [7:0] count
);

  logic [7:0] s;
  logic [7:0] inc;
  logic [7:0] s_next;

  always_ff @(posedge clk) begin
    if (rst) begin
      s <= 8'h00;
    end else begin
      s <= s_next;
    end
  end
  assign inc = s + 8'h01;
  assign s_next = en ? inc : s;

  assign count = s;
endmodule
