// generated by gin test fixtures
// theorem: Detector.detector_correct
module detector (
  input logic clk,
  input logic rst,
  input logic b,
  output logic hit
);

  logic [1:0] s;
  logic is0;
  logic is1;
  logic [1:0] pick10;
  logic [1:0] pick12;
  logic [1:0] s_inner;
  logic [1:0] s_next;
  logic hit_inner;
  logic o_hit;

  always_ff @(posedge clk) begin
    if (rst) begin
      s <= 2'h0;
    end else begin
      s <= s_next;
    end
  end
  assign is0 = s == 2'h0;
  assign is1 = s == 2'h1;
  assign pick10 = b ? 2'h1 : 2'h0;
  assign pick12 = b ? 2'h1 : 2'h2;
  assign s_inner = is1 ? pick12 : pick10;
  assign s_next = is0 ? pick10 : s_inner;
  assign hit_inner = is1 ? 1'b0 : b;
  assign o_hit = is0 ? 1'b0 : hit_inner;

  assign hit = o_hit;
endmodule
