// generated by gin test fixtures
// theorem: Mac.mac_correct
module mac (
  input logic clk,
  input logic rst,
  input logic [7:0] x,
  input logic [7:0] y,
  output logic [15:0] acc
);

  logic [15:0] acc_q;
  logic [15:0] xz;
  logic [15:0] yz;
  logic [15:0] prod;
  logic [15:0] sum;

  always_ff @(posedge clk) begin
    if (rst) begin
      acc_q <= 16'h0000;
    end else begin
      acc_q <= sum;
    end
  end
  assign xz = {{8{1'b0}}, x};
  assign yz = {{8{1'b0}}, y};
  assign prod = xz * yz;
  assign sum = acc_q + prod;

  assign acc = acc_q;
endmodule
