-- | Tests for the Verilog-2005 backend.
--
-- The tool-checked tests are shared with "Gin.Backend.SystemVerilogSpec"
-- through 'familySpec', which runs them against one 'Flavour' (backend,
-- language flags, golden directory). Tool runs follow the commands in
-- the backend interface: a private temporary directory holding
-- @<module>.<ext>@ and @<module>_tb.<ext>@.
--
-- Expected outputs for netlists other than the shared fixtures come from
-- 'referenceVectors', a cycle simulator written directly from the tables
-- in @docs/semantics.md@ and checked here against hand-computed values
-- and the fixtures' vectors.
module Gin.Backend.VerilogSpec
  ( spec
    -- * Shared with the SystemVerilog suite
  , Flavour (..)
  , familySpec
  , designWords
  , allNetlists
  ) where

import Control.Monad (forM_)
import Data.Bits (complement, shiftL, shiftR, xor, (.&.), (.|.))
import Data.ByteString qualified as ByteString
import Data.Char (isAsciiLower, isDigit, isHexDigit)
import Data.List (mapAccumL, sort, unsnoc, (!?))
import Data.Map.Lazy qualified as Map
import Data.Text (Text)
import Data.Text qualified as Text
import Data.Text.Encoding qualified as Text
import Gin.Backend.Types
import Gin.Backend.Verilog (verilog)
import Gin.Backend.Verilog.Testbench (hexDigits, literal, sizedHex)
import Gin.Core.Syntax (Port (..), Ty (..), Value (..))
import Gin.Examples
import Gin.Netlist.Types
import Gin.TestUtil
import Gin.Vectors (Cycle (..), Vectors (..), maxCycles)
import Numeric.Natural (Natural)
import System.Exit (ExitCode (..))
import System.FilePath ((</>))
import Test.Hspec

----------------------------------------------------------------------
-- Flavours

-- | One member of the Verilog family under test.
data Flavour = Flavour
  { flBackend :: Backend
  , flTag :: String
  -- ^ Prefix of the target-specific test tags: @v@ or @sv@.
  , flGoldenDir :: FilePath
  -- ^ Directory under @test/golden@.
  , flIcarusStd :: String
  -- ^ @iverilog@ language flag.
  , flVerilatorLanguage :: String
  -- ^ Verilator @--default-language@ value.
  }

verilogFlavour :: Flavour
verilogFlavour =
  Flavour
    { flBackend = verilog
    , flTag = "v"
    , flGoldenDir = "verilog"
    , flIcarusStd = "-g2005"
    , flVerilatorLanguage = "1364-2005"
    }

----------------------------------------------------------------------
-- Spec

spec :: Spec
spec = do
  describe "backend" $
    it "targets Verilog with the v extension" $ do
      backendTarget verilog `shouldBe` Verilog
      backendFileExt verilog `shouldBe` "v"
  familySpec verilogFlavour
  describe "literals" $ do
    it "prints bits as 1'b0 and 1'b1" $ do
      literal (HLitBit False) `shouldBe` "1'b0"
      literal (HLitBit True) `shouldBe` "1'b1"
    it "prints vectors as sized lowercase hex with ceil(w/4) digits" $ do
      literal (HLitVec 8 15) `shouldBe` "8'h0f"
      literal (HLitVec 1 1) `shouldBe` "1'h1"
      literal (HLitVec 13 0x1abc) `shouldBe` "13'h1abc"
      literal (HLitVec 16 0) `shouldBe` "16'h0000"
    it "prints a width-4096 vector with 1024 digits" $
      literal (HLitVec 4096 (2 ^ (4096 :: Int) - 1))
        `shouldBe` ("4096'h" <> Text.replicate 1024 "f")
    it "reduces out-of-range payloads modulo 2^width" $ do
      hexDigits 4 0x1f `shouldBe` "f"
      hexDigits 8 (-1) `shouldBe` "ff"
      sizedHex 3 8 `shouldBe` "3'h0"
  describe "dialect" $
    it "uses wire, reg and always, never SystemVerilog keywords" $ do
      let ws = concatMap (designWords . backendRender verilog) allNetlists
      filter (`elem` ["logic", "always_ff", "always_comb"]) ws `shouldBe` []
      filter (`elem` ["wire", "reg", "always"]) ws `shouldSatisfy` (not . null)
  describe "reference simulator" $ do
    it "reproduces the shared fixture vectors" $
      forM_ examples $ \(_, m, vs) ->
        referenceVectors m (fmap cycInputs (vecCycles vs)) `shouldBe` vs
    it "matches hand-computed operator results" $
      forM_ handComputed $ \(ty, e, expected) -> do
        let vs = referenceVectors (oneOp ty e) [[VBV 8 0xb6, VBV 8 0x05, VBool True]]
        fmap cycOutputs (vecCycles vs) `shouldBe` [[expected]]

-- | Tests every Verilog-family backend must pass.
familySpec :: Flavour -> Spec
familySpec fl = do
  describe "design files" $ do
    forM_ examples $ \(name, m, _) ->
      it (tag "golden" <> " " <> name <> " matches its golden file") $
        goldenText (golden name) (render m)
    forM_ extraNetlists $ \m ->
      it (tag "golden" <> " " <> moduleName m <> " matches its golden file") $
        goldenText (golden (moduleName m)) (render m)
    it "starts with the header lines as line comments" $
      take 2 (Text.lines (render counterNetlist))
        `shouldBe` ["// generated by gin test fixtures", "// theorem: Counter.counter_correct"]
    it "keeps a header line with line breaks inside one comment" $ do
      let m = counterNetlist {modHeader = ["a\nassign count = 8'h00;", "b\rc\x2028" <> "d"]}
          ls = Text.lines (render m)
      take 2 ls `shouldSatisfy` all ("// " `Text.isPrefixOf`)
      ls !? 2 `shouldBe` Just "module counter ("
      filter (Text.any (`elem` ['\r', '\x2028'])) ls `shouldBe` []
    it "defines exactly one module, named after the netlist" $
      forM_ (allNetlists <> [wideNetlist]) $ \m ->
        filter ("module " `Text.isPrefixOf`) (Text.lines (render m))
          `shouldBe` ["module " <> unIdent (modName m) <> " ("]
    it "lists ports in the order clock, reset, inputs, outputs" $
      portNames (render macNetlist) `shouldBe` ["clk", "rst", "x", "y", "acc"]
    it "folds a slice of a constant operand into a literal" $
      render (oneOp (HVec 4) (HSlice 6 3 (vecC 8 0xb6)))
        `shouldSatisfy` Text.isInfixOf "assign n = 4'h6;"
    it "prints a zero-extension to the same width as the plain operand" $
      render (oneOp (HVec 8) (HZext 8 (ref "a"))) `shouldSatisfy` Text.isInfixOf "assign n = a;"
    it "[v-coverage] prints every constant operand as a sized literal" $
      forM_ (allNetlists <> [wideNetlist]) $ \m ->
        concatMap unsizedNumbers (codeLines (render m)) `shouldBe` []
  describe "testbench files" $ do
    forM_ examples $ \(name, m, vs) ->
      it (name <> " testbench matches its golden file") $
        goldenText (golden (name <> "_tb")) (testbench m vs)
    it "never passes a literal to $display" $
      forM_ examples $ \(_, m, vs) ->
        [ l
        | l <- Text.lines (testbench m vs)
        , "$display" `Text.isInfixOf` l
        , "'" `Text.isInfixOf` l
        ]
          `shouldBe` []
    it "drives a missing or ill-typed input value as all X" $ do
      let vs = macVectors {vecCycles = zipWith blank [0 :: Int ..] (vecCycles macVectors)}
          blank i c = if i == 1 then c {cycInputs = [VBool True]} else c
          cycle1 = takeWhile (/= "// cycle 2") (dropWhile (/= "// cycle 1") (strippedLines vs))
          strippedLines = fmap Text.strip . Text.lines . testbench macNetlist
      filter (Text.isSuffixOf "'bx;") cycle1 `shouldBe` ["x = 8'bx;", "y = 8'bx;"]
    it "names its module <name>_tb and uses a 1 ns time unit" $ do
      let ls = Text.lines (testbench counterNetlist counterVectors)
      filter ("`timescale" `Text.isPrefixOf`) ls `shouldBe` ["`timescale 1ns/1ps"]
      filter ("module " `Text.isPrefixOf`) ls `shouldBe` ["module counter_tb;"]
  describe "lint" $
    forM_ examples $ \(name, m, _) ->
      itWithTools lintTools (tag "lint" <> " " <> name <> " passes Verilator -Wall and iverilog") $
        lintClean fl m
  describe "simulation" $ do
    forM_ examples $ \(name, m, vs) ->
      itWithTools simTools (tag "tb-pass" <> " " <> name <> " testbench prints GIN-PASS") $
        simulate fl m vs >>= shouldPass (length (vecCycles vs))
    itWithTools simTools (tag "tb-pass" <> " a testbench with the most cycles allowed passes") $
      simulate fl delayNetlist delayVectors >>= shouldPass maxCycles
  describe "failing testbenches" $ do
    itWithTools simTools "[v-tb-fail] corrupted expected values print mismatches and GIN-FAIL" $ do
      let vs = corruptOutput 5 (VBV 8 9) (corruptOutput 3 (VBV 8 7) counterVectors)
      result <- simulate fl counterNetlist vs
      markerLines result
        `shouldBe` [ "GIN-MISMATCH cycle=3 port=count expected=07 got=02"
                   , "GIN-MISMATCH cycle=5 port=count expected=09 got=03"
                   , "GIN-FAIL mismatches=2"
                   ]
    itWithTools simTools "[v-tb-fail] a corrupted Bool expected value fails" $ do
      result <- simulate fl detectorNetlist (corruptOutput 2 (VBool False) detectorVectors)
      markerLines result
        `shouldBe` ["GIN-MISMATCH cycle=2 port=hit expected=0 got=1", "GIN-FAIL mismatches=1"]
    itWithTools simTools "[v-tb-fail] a design that diverges from the vectors fails" $ do
      let buggy = counterNetlist {modDecls = fmap incByTwo (modDecls counterNetlist)}
          incByTwo = \case
            DAssign n (HBin BAdd a _) -> DAssign n (HBin BAdd a (vecC 8 2))
            d -> d
      result <- simulate fl buggy counterVectors
      markerLines result
        `shouldBe` zipWith3
          mismatch
          [1 :: Int ..]
          ["01", "02", "02", "03", "03", "03", "04"]
          ["02", "04", "04", "06", "06", "06", "08"]
        <> ["GIN-FAIL mismatches=7"]
    itWithTools simTools "[v-tb-fail] an undefined output value counts as a mismatch" $ do
      let design = Text.replace "assign count = s;" "assign count = 8'bx;" (render counterNetlist)
      design `shouldNotBe` render counterNetlist
      result <- simulateText fl "counter" design (testbench counterNetlist counterVectors)
      markerLines result
        `shouldBe` zipWith3
          mismatch
          [0 :: Int ..]
          ["00", "01", "02", "02", "03", "03", "03", "04"]
          (repeat "xx")
        <> ["GIN-FAIL mismatches=8"]
    itWithTools simTools "[v-tb-fail] a row missing its expected value counts as a mismatch" $ do
      let vs = counterVectors {vecCycles = zipWith dropAt [0 :: Int ..] (vecCycles counterVectors)}
          dropAt i c = if i == 4 then c {cycOutputs = []} else c
      result <- simulate fl counterNetlist vs
      markerLines result
        `shouldBe` ["GIN-MISMATCH cycle=4 port=count expected=none got=03", "GIN-FAIL mismatches=1"]
  describe "operator coverage" $ do
    itWithTools lintTools "[v-coverage] a netlist using every operator lints clean" $
      lintClean fl allOpsNetlist
    itWithTools simTools "[v-coverage] a netlist using every operator simulates correctly" $
      simulate fl allOpsNetlist allOpsVectors >>= shouldPass (length (vecCycles allOpsVectors))
  describe "extreme widths" $ do
    itWithTools lintTools "[v-wide] width-4096 and width-1 vectors lint clean" $
      lintClean fl wideNetlist
    itWithTools simTools "[v-wide] width-4096 and width-1 vectors pass under iverilog" $
      simulate fl wideNetlist wideVectors >>= shouldPass (length (vecCycles wideVectors))
  describe "lint suppressions" $ do
    itWithTools lintTools "[v-unused] a register-free module lints clean" $
      lintClean fl combNetlist
    it "[v-unused] a register-free module suppresses exactly clk and rst" $
      suppressed (render combNetlist) `shouldBe` ["clk", "rst"]
    itWithTools lintTools "[v-unused] unread and partly read signals lint clean" $
      lintClean fl spareNetlist
    it "[v-unused] suppresses exactly the unread input and the partly read signals" $
      suppressed (render spareNetlist) `shouldBe` ["b", "c", "t"]
    it "[v-unused] suppresses nothing in the shared fixtures" $
      forM_ examples $ \(_, m, _) -> suppressed (render m) `shouldBe` []
    itWithTools ["verilator"] "[v-unused] without the pragmas Verilator warns about those signals" $
      forM_ [combNetlist, spareNetlist] $ \m -> do
        warnings <- verilatorWarnings fl m (stripPragmas (render m))
        sort warnings `shouldBe` sort (fmap ("UNUSEDSIGNAL",) (suppressed (render m)))
    itWithTools simTools "[v-unused] a register-free module simulates correctly" $
      simulate fl combNetlist combVectors >>= shouldPass (length (vecCycles combVectors))
  where
    tag t = "[" <> flTag fl <> "-" <> t <> "]"
    b = flBackend fl
    render = backendRender b
    testbench = backendTestbench b
    golden name = flGoldenDir fl </> name <> "." <> backendFileExt b
    mismatch t expected got =
      Text.concat
        ["GIN-MISMATCH cycle=", Text.pack (show t), " port=count expected=", expected, " got=", got]

----------------------------------------------------------------------
-- Tool runs

lintTools, simTools :: [String]
lintTools = ["verilator", "iverilog"]
simTools = ["iverilog", "vvp"]

designFile, benchFile :: Flavour -> Text -> FilePath
designFile fl name = Text.unpack name <> "." <> backendFileExt (flBackend fl)
benchFile fl name = Text.unpack name <> "_tb." <> backendFileExt (flBackend fl)

writeUtf8 :: FilePath -> Text -> IO ()
writeUtf8 path = ByteString.writeFile path . Text.encodeUtf8

verilatorArgs :: Flavour -> FilePath -> [String]
verilatorArgs fl file = ["--lint-only", "-Wall", "--default-language", flVerilatorLanguage fl, file]

-- | Both lint commands exit 0; Verilator prints no warning or error line
-- (only its statistics report) and iverilog prints nothing.
lintClean :: Flavour -> Module -> Expectation
lintClean fl m = withTempDir $ \dir -> do
  let file = designFile fl (unIdent (modName m))
  writeUtf8 (dir </> file) (backendRender (flBackend fl) m)
  (code, out, err) <- runTool dir "verilator" (verilatorArgs fl file)
  (code, filter ("%" `Text.isPrefixOf`) (Text.lines (out <> err))) `shouldBe` (ExitSuccess, [])
  icarusRun <- runTool dir "iverilog" [flIcarusStd fl, "-o", "/dev/null", file]
  combined icarusRun `shouldBe` (ExitSuccess, "")

-- | Verilator @-Wall@ warnings on a design text, as (code, signal) pairs.
verilatorWarnings :: Flavour -> Module -> Text -> IO [(Text, Text)]
verilatorWarnings fl m design = withTempDir $ \dir -> do
  let file = designFile fl (unIdent (modName m))
  writeUtf8 (dir </> file) design
  (_, out, err) <- runTool dir "verilator" (verilatorArgs fl file)
  pure
    [ (code, Text.takeWhile (/= '\'') (Text.drop 1 (snd (Text.breakOn "'" msg))))
    | l <- Text.lines (out <> err)
    , Just rest <- [Text.stripPrefix "%Warning-" l]
    , let (code, msg) = Text.breakOn ":" rest
    ]

-- | Compile the design and testbench with iverilog, which must be silent,
-- and run the result under vvp.
simulate :: Flavour -> Module -> Vectors -> IO (ExitCode, Text, Text)
simulate fl m vs =
  simulateText fl (unIdent (modName m)) (backendRender b m) (backendTestbench b m vs)
  where
    b = flBackend fl

simulateText :: Flavour -> Text -> Text -> Text -> IO (ExitCode, Text, Text)
simulateText fl name design bench = withTempDir $ \dir -> do
  writeUtf8 (dir </> designFile fl name) design
  writeUtf8 (dir </> benchFile fl name) bench
  compiled <-
    runTool dir "iverilog" [flIcarusStd fl, "-o", "tb.vvp", designFile fl name, benchFile fl name]
  combined compiled `shouldBe` (ExitSuccess, "")
  runTool dir "vvp" ["-n", "tb.vvp"]

combined :: (ExitCode, Text, Text) -> (ExitCode, Text)
combined (code, out, err) = (code, out <> err)

-- | The pass rule of @docs/semantics.md@: exit 0, exactly one
-- @GIN-PASS cycles=<n>@ line, and no failure or mismatch line.
shouldPass :: Int -> (ExitCode, Text, Text) -> Expectation
shouldPass n result@(code, _, _) = do
  markerLines result `shouldBe` [passMarker <> " cycles=" <> Text.pack (show n)]
  code `shouldBe` ExitSuccess

-- | Standard-output lines that carry a protocol marker.
markerLines :: (ExitCode, Text, Text) -> [Text]
markerLines (_, out, _) =
  [l | l <- Text.lines out, any (`Text.isInfixOf` l) [passMarker, failMarker, mismatchMarker]]

----------------------------------------------------------------------
-- Inspecting generated text

-- | Names declared between @lint_off@ and @lint_on@ pragmas, in order.
suppressed :: Text -> [Text]
suppressed = go False . fmap Text.strip . Text.lines
  where
    go inside = \case
      [] -> []
      l : ls
        | l == lintOff -> go True ls
        | l == lintOn -> go False ls
        | inside -> lastWord (Text.dropWhileEnd (`elem` [',', ';']) l) : go inside ls
        | otherwise -> go inside ls

stripPragmas :: Text -> Text
stripPragmas = Text.unlines . filter ((`notElem` [lintOff, lintOn]) . Text.strip) . Text.lines

lintOff, lintOn :: Text
lintOff = "/* verilator lint_off UNUSEDSIGNAL */"
lintOn = "/* verilator lint_on UNUSEDSIGNAL */"

lastWord :: Text -> Text
lastWord = maybe "" snd . unsnoc . Text.words

-- | Port names in declaration order.
portNames :: Text -> [Text]
portNames design =
  [ lastWord (Text.dropWhileEnd (== ',') l)
  | l <- fmap Text.strip (Text.lines design)
  , any (`Text.isPrefixOf` l) ["input ", "output "]
  ]

-- | Lines that are neither comments nor pragmas.
codeLines :: Text -> [Text]
codeLines =
  filter (\l -> not (any (`Text.isPrefixOf` Text.stripStart l) ["//", "/*"])) . Text.lines

-- | Identifier-like words of the code lines (keywords and names).
designWords :: Text -> [Text]
designWords = concatMap (filter (not . Text.null) . Text.split (not . isWordChar)) . codeLines
  where
    isWordChar c = isAsciiLower c || isDigit c || c == '_'

-- | Decimal numbers that are not part of a sized literal, a bit index or
-- a replication count.
unsizedNumbers :: Text -> [Text]
unsizedNumbers = go . Text.unpack
  where
    go = \case
      [] -> []
      s@(c : cs)
        | isAsciiLower c || c == '_' -> go (dropWhile isWordChar s)
        | isDigit c ->
            let (ds, rest) = span isDigit s
             in case rest of
                  '\'' : base : more
                    | base `elem` ("bh" :: String) -> go (dropWhile isLitDigit more)
                  r : _ | r `elem` ("{:]" :: String) -> go rest
                  _ -> Text.pack ds : go rest
        | otherwise -> go cs
    isWordChar x = isAsciiLower x || isDigit x || x == '_'
    isLitDigit x = isHexDigit x || x == 'x'

----------------------------------------------------------------------
-- Reference simulator

-- | The vectors a netlist produces for the given input rows, following
-- the cycle semantics and primitive table of @docs/semantics.md@.
referenceVectors :: Module -> [[Value]] -> Vectors
referenceVectors m rows =
  Vectors
    { vecTop = unIdent (modName m)
    , vecInputs = fmap port (modInputs m)
    , vecOutputs = fmap (port . outNet) (modOutputs m)
    , vecCycles = snd (mapAccumL step initialRegs rows)
    }
  where
    port n = Port (unIdent (netName n)) (portTy (netType n))
    portTy = \case
      HBit -> TBool
      HVec w -> TBitVec w
    widths = moduleNets m
    initialRegs = Map.fromList [(netName n, litBits r) | DReg n r _ <- modDecls m]
    step regs row = (next, Cycle row outs)
      where
        -- Lazy in the values, so combinational nets may appear in any order.
        env =
          Map.unions
            [ Map.fromList (zip (fmap netName (modInputs m)) (fmap valueBits row))
            , regs
            , Map.fromList [(netName n, evalExpr e) | DAssign n e <- modDecls m]
            ]
        next = Map.fromList [(netName n, val o) | DReg n _ o <- modDecls m]
        outs = [toValue (netType n) (val o) | Output n o <- modOutputs m]
        val = \case
          ORef i -> Map.findWithDefault 0 i env
          OConst l -> litBits l
        width = \case
          ORef i -> maybe 1 hwWidth (Map.lookup i widths)
          OConst l -> hwWidth (hlitType l)
        evalExpr = \case
          HOperand o -> val o
          HUn UNot o -> wrap (width o) (complement (val o))
          HUn UNeg o -> wrap (width o) (negate (val o))
          HBin op x y -> binary op (width x) (val x) (val y)
          HMux c t e -> if val c /= 0 then val t else val e
          HShl k o -> wrap (width o) (val o `shiftL` fromIntegral k)
          HLshr k o -> val o `shiftR` fromIntegral k
          HSlice hi lo o -> wrap (hi - lo + 1) (val o `shiftR` fromIntegral lo)
          HConcat x y -> (val x `shiftL` fromIntegral (width y)) .|. val y
          HZext _ o -> val o
          HBitToVec o -> val o
    binary op w x y = case op of
      BAnd -> x .&. y
      BOr -> x .|. y
      BXor -> x `xor` y
      BAdd -> wrap w (x + y)
      BSub -> wrap w (x - y)
      BMul -> wrap w (x * y)
      BEq -> fromBool (x == y)
      BUlt -> fromBool (x < y)
      BUle -> fromBool (x <= y)
    fromBool c = if c then 1 else 0
    wrap :: Natural -> Integer -> Integer
    wrap w x = x `mod` (2 ^ w)
    litBits = \case
      HLitBit c -> fromBool c
      HLitVec _ x -> x
    valueBits = \case
      VBool c -> fromBool c
      VBV _ x -> x
      VTuple _ -> 0
    toValue ty x = case ty of
      HBit -> VBool (x /= 0)
      HVec w -> VBV w x

-- | A module computing one operator over inputs @a@, @b@ (8 bits) and
-- @p@ (Bool), output @y@.
oneOp :: HwType -> HExpr -> Module
oneOp ty e =
  mkModule
    "op"
    [net "a" (HVec 8), net "b" (HVec 8), net "p" HBit]
    [Output (net "y" ty) (ref "n")]
    [DAssign (net "n" ty) e]

-- | Operator results for a = 0xb6, b = 0x05, p = true, computed by hand.
handComputed :: [(HwType, HExpr, Value)]
handComputed =
  [ (HVec 8, HOperand (vecC 8 0x5a), VBV 8 0x5a)
  , (HVec 8, HUn UNot (ref "a"), VBV 8 0x49)
  , (HBit, HUn UNot (ref "p"), VBool False)
  , (HVec 8, HUn UNeg (ref "b"), VBV 8 0xfb)
  , (HVec 8, HUn UNeg (vecC 8 0), VBV 8 0)
  , (HVec 8, HBin BAnd (ref "a") (ref "b"), VBV 8 0x04)
  , (HVec 8, HBin BOr (ref "a") (ref "b"), VBV 8 0xb7)
  , (HVec 8, HBin BXor (ref "a") (ref "b"), VBV 8 0xb3)
  , (HVec 8, HBin BAdd (ref "a") (vecC 8 0x60), VBV 8 0x16)
  , (HVec 8, HBin BSub (ref "b") (ref "a"), VBV 8 0x4f)
  , (HVec 8, HBin BMul (ref "a") (ref "b"), VBV 8 0x8e)
  , (HBit, HBin BEq (ref "a") (ref "b"), VBool False)
  , (HBit, HBin BEq (ref "a") (vecC 8 0xb6), VBool True)
  , (HBit, HBin BUlt (ref "b") (ref "a"), VBool True)
  , (HBit, HBin BUlt (ref "a") (vecC 8 0xb6), VBool False)
  , (HBit, HBin BUle (ref "a") (vecC 8 0xb6), VBool True)
  , (HBit, HBin BUle (ref "a") (ref "b"), VBool False)
  , (HVec 8, HMux (ref "p") (ref "a") (ref "b"), VBV 8 0xb6)
  , (HVec 8, HMux (bitC False) (ref "a") (ref "b"), VBV 8 0x05)
  , (HVec 8, HShl 3 (ref "a"), VBV 8 0xb0)
  , (HVec 8, HShl 7 (ref "b"), VBV 8 0x80)
  , (HVec 8, HLshr 3 (ref "a"), VBV 8 0x16)
  , (HVec 4, HSlice 6 3 (ref "a"), VBV 4 0x6)
  , (HVec 1, HSlice 7 7 (ref "a"), VBV 1 1)
  , (HVec 16, HConcat (ref "a") (ref "b"), VBV 16 0xb605)
  , (HVec 12, HConcat (vecC 4 0xa) (ref "b"), VBV 12 0xa05)
  , (HVec 12, HZext 12 (ref "a"), VBV 12 0xb6)
  , (HVec 1, HBitToVec (ref "p"), VBV 1 1)
  ]

----------------------------------------------------------------------
-- Netlists

examples :: [(FilePath, Module, Vectors)]
examples =
  [ ("counter", counterNetlist, counterVectors)
  , ("mac", macNetlist, macVectors)
  , ("detector", detectorNetlist, detectorVectors)
  ]

-- | Netlists with a golden design file beyond the shared fixtures.
extraNetlists :: [Module]
extraNetlists = [allOpsNetlist, combNetlist, spareNetlist]

-- | Every netlist of this suite except the width-4096 one.
allNetlists :: [Module]
allNetlists = [counterNetlist, macNetlist, detectorNetlist] <> extraNetlists

moduleName :: Module -> FilePath
moduleName = Text.unpack . unIdent . modName

mkModule :: Text -> [Net] -> [Output] -> [Decl] -> Module
mkModule name ins outs decls =
  Module
    { modName = Ident name
    , modHeader = ["generated by the backend test suite"]
    , modClock = Ident "clk"
    , modReset = Ident "rst"
    , modInputs = ins
    , modOutputs = outs
    , modDecls = decls
    }

net :: Text -> HwType -> Net
net = Net . Ident

ref :: Text -> Operand
ref = ORef . Ident

vecC :: Natural -> Integer -> Operand
vecC w = OConst . HLitVec w

bitC :: Bool -> Operand
bitC = OConst . HLitBit

-- | An output port @o_<net>@ for every declared net.
observeAll :: [Decl] -> [Output]
observeAll decls =
  [ Output (Net (Ident ("o_" <> unIdent (netName n))) (netType n)) (ORef (netName n))
  | n <- fmap declNet decls
  ]

-- | Every 'HExpr', 'BinOp' and 'UnOp' constructor, with a constant in
-- every operand position the netlist invariants allow, on HBit and HVec
-- operands; registers with Bool, vector and constant next values; and
-- outputs driven by constants and by an input. Every net is an output.
allOpsNetlist :: Module
allOpsNetlist =
  mkModule
    "allops"
    [net "a" v8, net "b" v8, net "p" HBit, net "q" HBit]
    ( observeAll decls
        <> [ Output (net "o_k8" v8) (vecC 8 0x3c)
           , Output (net "o_kb" HBit) (bitC False)
           , Output (net "o_q" HBit) (ref "q")
           ]
    )
    decls
  where
    v8 = HVec 8
    decls = registers <> zipWith numbered [0 :: Int ..] exprs
    numbered i (ty, e) = DAssign (net ("n" <> Text.pack (show i)) ty) e
    registers =
      [ DReg (net "acc" v8) (HLitVec 8 0xa5) (ref "acc_next")
      , DAssign (net "acc_next" v8) (HBin BAdd (ref "acc") (ref "a"))
      , DAssign (net "acc_hi" (HVec 3)) (HSlice 7 5 (ref "acc"))
      , DReg (net "flag" HBit) (HLitBit True) (ref "p")
      , DReg (net "held" (HVec 4)) (HLitVec 4 3) (vecC 4 9)
      ]
    resultTy op = if op `elem` [BEq, BUlt, BUle] then HBit else v8
    exprs =
      [ (v8, HOperand (ref "a"))
      , (v8, HOperand (vecC 8 0x5a))
      , (HBit, HOperand (bitC True))
      , (v8, HUn UNot (ref "a"))
      , (v8, HUn UNot (vecC 8 0x0f))
      , (HBit, HUn UNot (ref "p"))
      , (HBit, HUn UNot (bitC False))
      , (v8, HUn UNeg (ref "a"))
      , (v8, HUn UNeg (vecC 8 1))
      ]
        <> concat
          [ [ (resultTy op, HBin op (ref "a") (ref "b"))
            , (resultTy op, HBin op (vecC 8 0xc3) (ref "b"))
            , (resultTy op, HBin op (ref "a") (vecC 8 0x3c))
            ]
          | op <- [minBound .. maxBound]
          ]
        <> concat
          [ [ (HBit, HBin op (ref "p") (ref "q"))
            , (HBit, HBin op (bitC True) (ref "q"))
            , (HBit, HBin op (ref "p") (bitC False))
            ]
          | op <- [BAnd, BOr, BXor, BEq]
          ]
        <> [ (v8, HMux (ref "p") (ref "a") (ref "b"))
           , (v8, HMux (bitC True) (ref "a") (ref "b"))
           , (v8, HMux (ref "p") (vecC 8 0x11) (ref "b"))
           , (v8, HMux (ref "p") (ref "a") (vecC 8 0x22))
           , (HBit, HMux (ref "q") (ref "p") (bitC True))
           , (v8, HShl 0 (ref "a"))
           , (v8, HShl 3 (ref "a"))
           , (v8, HShl 7 (ref "a"))
           , (v8, HShl 2 (vecC 8 0x81))
           , (v8, HLshr 0 (ref "a"))
           , (v8, HLshr 3 (ref "a"))
           , (v8, HLshr 7 (ref "a"))
           , (v8, HLshr 5 (vecC 8 0xf0))
           , (HVec 4, HSlice 7 4 (ref "a"))
           , (HVec 1, HSlice 0 0 (ref "b"))
           , (v8, HSlice 7 0 (ref "a"))
           , (HVec 16, HConcat (ref "a") (ref "b"))
           , (HVec 12, HConcat (vecC 4 0xa) (ref "b"))
           , (HVec 9, HConcat (ref "a") (vecC 1 1))
           , (HVec 16, HZext 16 (ref "a"))
           , (v8, HZext 8 (ref "b"))
           , (HVec 12, HZext 12 (vecC 8 0xff))
           , (HVec 1, HBitToVec (ref "p"))
           , (HVec 1, HBitToVec (bitC True))
           ]

-- | Edge values first, then pseudo-random rows.
allOpsVectors :: Vectors
allOpsVectors = referenceVectors allOpsNetlist (edges <> fmap row (take 28 (pseudoRandom 7)))
  where
    edges =
      [ [VBV 8 0, VBV 8 0, VBool False, VBool False]
      , [VBV 8 255, VBV 8 255, VBool True, VBool True]
      , [VBV 8 255, VBV 8 1, VBool True, VBool False]
      , [VBV 8 128, VBV 8 128, VBool False, VBool True]
      ]
    row r =
      [ VBV 8 (r `mod` 256)
      , VBV 8 ((r `shiftR` 8) `mod` 256)
      , VBool (odd (r `shiftR` 16))
      , VBool (odd (r `shiftR` 17))
      ]

pseudoRandom :: Integer -> [Integer]
pseudoRandom = fmap (`shiftR` 8) . drop 1 . iterate lcg
  where
    lcg x = (x * 1103515245 + 12345) `mod` 2147483648

-- | A width-4096 input, register and outputs next to width-1 vectors.
wideNetlist :: Module
wideNetlist =
  mkModule "wide" [net "a" w, net "s" (HVec 1), net "p" HBit] (observeAll decls) decls
  where
    w = HVec 4096
    decls =
      [ DReg (net "big" w) (HLitVec 4096 widePattern) (ref "a")
      , DAssign (net "mixed" w) (HBin BXor (ref "big") (vecC 4096 (widePattern `shiftR` 4)))
      , DAssign (net "total" w) (HBin BAdd (ref "a") (vecC 4096 (2 ^ (4096 :: Int) - 1)))
      , DAssign (net "same" HBit) (HBin BEq (ref "a") (vecC 4096 widePattern))
      , DAssign (net "s_inc" (HVec 1)) (HBin BAdd (ref "s") (vecC 1 1))
      , DAssign (net "s_wide" w) (HZext 4096 (ref "s"))
      , DAssign (net "p_vec" (HVec 1)) (HBitToVec (ref "p"))
      , DAssign (net "top" (HVec 8)) (HSlice 4095 4088 (ref "total"))
      ]

widePattern :: Integer
widePattern = foldl (\acc _ -> acc * 2 ^ (64 :: Int) + 0xfedcba9876543210) 0 [1 .. 64 :: Int]

wideVectors :: Vectors
wideVectors =
  referenceVectors
    wideNetlist
    [ [VBV 4096 0, VBV 1 0, VBool False]
    , [VBV 4096 (2 ^ (4096 :: Int) - 1), VBV 1 1, VBool True]
    , [VBV 4096 widePattern, VBV 1 1, VBool False]
    , [VBV 4096 12345, VBV 1 0, VBool True]
    ]

-- | No registers: the clock and reset are unread.
combNetlist :: Module
combNetlist =
  mkModule
    "comb"
    [net "a" (HVec 4)]
    [Output (net "y" (HVec 4)) (ref "na")]
    [DAssign (net "na" (HVec 4)) (HUn UNot (ref "a"))]

combVectors :: Vectors
combVectors = referenceVectors combNetlist [[VBV 4 x] | x <- [0, 5, 15, 10]]

-- | A one-cycle delay of a Bool input.
delayNetlist :: Module
delayNetlist =
  mkModule
    "delay"
    [net "a" HBit]
    [Output (net "y" HBit) (ref "q")]
    [DReg (net "q" HBit) (HLitBit False) (ref "a")]

-- | 'maxCycles' cycles (200000 payload bits, within 'Gin.Limits.maxVectorBits').
delayVectors :: Vectors
delayVectors =
  referenceVectors delayNetlist [[VBool (odd r)] | r <- take maxCycles (pseudoRandom 3)]

-- | Input @b@ is unread, input @c@ and net @t@ are partly read; input
-- @d@ is read completely, but only through two slices.
spareNetlist :: Module
spareNetlist =
  mkModule
    "spare"
    [net "a" v8, net "b" HBit, net "c" v8, net "d" v8]
    [ Output (net "o_c" (HVec 4)) (ref "c_lo")
    , Output (net "o_dh" (HVec 4)) (ref "d_hi")
    , Output (net "o_dl" (HVec 4)) (ref "d_lo")
    , Output (net "o_m" (HVec 1)) (ref "t_msb")
    ]
    [ DAssign (net "c_lo" (HVec 4)) (HSlice 3 0 (ref "c"))
    , DAssign (net "d_hi" (HVec 4)) (HSlice 7 4 (ref "d"))
    , DAssign (net "d_lo" (HVec 4)) (HSlice 3 0 (ref "d"))
    , DReg (net "q" v8) (HLitVec 8 0) (ref "a")
    , DAssign (net "t" v8) (HBin BXor (ref "q") (ref "a"))
    , DAssign (net "t_msb" (HVec 1)) (HSlice 7 7 (ref "t"))
    ]
  where
    v8 = HVec 8

----------------------------------------------------------------------
-- Vector edits

-- | Replace the first expected output of cycle @t@.
corruptOutput :: Int -> Value -> Vectors -> Vectors
corruptOutput t v vs = vs {vecCycles = zipWith corrupt [0 ..] (vecCycles vs)}
  where
    corrupt i c = if i == t then c {cycOutputs = v : drop 1 (cycOutputs c)} else c

