-- | Hand-written example circuits at every pipeline level, shared by all
-- component test suites: I keep them here so each package can be tested in
-- isolation.
--
-- These mirror, but are not byte-identical to, what the Lean exporter emits
-- for the same circuits.
module Gin.Examples
  ( -- * Shared
    sysDomain
  , testCertificate
  , bv
  , sig
    -- * counter: 8-bit enable counter, output is the current count
  , counterProgram
  , counterNormal
  , counterNetlist
  , counterVectors
    -- * mac: 8x8 -> 16 multiply-accumulate, output is the accumulator
  , macProgram
  , macNormal
  , macNetlist
  , macVectors
    -- * detector: overlapping "101" sequence detector (Mealy output)
  , detectorProgram
  , detectorNormal
  , detectorNetlist
  , detectorVectors
  ) where

import Data.Text (Text)
import Gin.Core.Normal
import Gin.Core.Syntax
import Gin.Netlist.Types
import Gin.Vectors (Cycle (..), Vectors (..))
import Numeric.Natural (Natural)

sysDomain :: Domain
sysDomain = Domain "System" 10000

testCertificate :: Text -> Certificate
testCertificate thm =
  Certificate
    { certTheorem = thm
    , certStatement = "(hand-written test fixture)"
    , certAxioms = ["propext"]
    , certImplAxioms = []
    , certSpecDefs = []
    }

producer :: Producer
producer = Producer "gin-test-examples" "n/a"

bv :: Natural -> Ty
bv = TBitVec

sig :: Ty -> Ty
sig = TSignal "System"

prim :: PrimOp -> [Ty] -> Ty -> Expr
prim op args res = EPrim op (tFuns args res)

v :: Text -> Expr
v = EVar . Name

----------------------------------------------------------------------
-- counter

-- > counter en = mealy (\s e -> (if e then s + 1 else s, s)) 0 en
counterProgram :: Program
counterProgram =
  Program
    { progProducer = producer
    , progTop =
        TopEntity
          { topName = "counter"
          , topDomain = sysDomain
          , topInputs = [Port "en" TBool]
          , topOutputs = [Port "count" (bv 8)]
          , topDef = "Counter.counter"
          }
    , progDefs = [Def "Counter.counter" (TFun (sig TBool) (sig (bv 8))) body]
    , progCertificate = testCertificate "Counter.counter_correct"
    }
  where
    body =
      ELam [("en", sig TBool)] $
        EApp (prim (SigMealy (VBV 8 0)) [stepTy, sig TBool] (sig (bv 8))) [step, v "en"]
    stepTy = tFuns [bv 8, TBool] (TProd [bv 8, bv 8])
    step =
      ELam [("s", bv 8), ("e", TBool)] $
        ETuple
          [ EIf (v "e") (EApp (prim BvAdd [bv 8, bv 8] (bv 8)) [v "s", ELit (VBV 8 1)]) (v "s")
          , v "s"
          ]

counterNormal :: NModule
counterNormal =
  NModule
    { nmName = "counter"
    , nmDomain = sysDomain
    , nmInputs = [("en", TBool)]
    , nmOutputs = [NOutput "count" (bv 8) (AVar "s")]
    , nmBinds =
        [ NBind "s" (bv 8) (NReg (VBV 8 0) (AVar "s_next"))
        , NBind "inc" (bv 8) (NPrim BvAdd [AVar "s", ALit (VBV 8 1)])
        , NBind "s_next" (bv 8) (NMux (AVar "en") (AVar "inc") (AVar "s"))
        ]
    , nmCertificate = testCertificate "Counter.counter_correct"
    }

counterNetlist :: Module
counterNetlist =
  Module
    { modName = Ident "counter"
    , modHeader = ["generated by gin test fixtures", "theorem: Counter.counter_correct"]
    , modClock = Ident "clk"
    , modReset = Ident "rst"
    , modInputs = [Net (Ident "en") HBit]
    , modOutputs = [Output (Net (Ident "count") (HVec 8)) (ORef (Ident "s"))]
    , modDecls =
        [ DReg (Net (Ident "s") (HVec 8)) (HLitVec 8 0) (ORef (Ident "s_next"))
        , DAssign (Net (Ident "inc") (HVec 8)) (HBin BAdd (ORef (Ident "s")) (OConst (HLitVec 8 1)))
        , DAssign (Net (Ident "s_next") (HVec 8)) (HMux (ORef (Ident "en")) (ORef (Ident "inc")) (ORef (Ident "s")))
        ]
    }

-- | en = 1 1 0 1 0 0 1 1; count = 0 1 2 2 3 3 3 4.
counterVectors :: Vectors
counterVectors =
  Vectors
    { vecTop = "counter"
    , vecInputs = [Port "en" TBool]
    , vecOutputs = [Port "count" (bv 8)]
    , vecCycles =
        zipWith
          (\e c -> Cycle [VBool e] [VBV 8 c])
          [True, True, False, True, False, False, True, True]
          [0, 1, 2, 2, 3, 3, 3, 4]
    }

----------------------------------------------------------------------
-- mac

-- > mac x y = mealy (\acc p -> let acc' = acc + zext16 p.1 * zext16 p.2 in (acc', acc)) 0
-- >                 (lift2 (,) x y)
macProgram :: Program
macProgram =
  Program
    { progProducer = producer
    , progTop =
        TopEntity
          { topName = "mac"
          , topDomain = sysDomain
          , topInputs = [Port "x" (bv 8), Port "y" (bv 8)]
          , topOutputs = [Port "acc" (bv 16)]
          , topDef = "Mac.mac"
          }
    , progDefs = [Def "Mac.mac" (tFuns [sig (bv 8), sig (bv 8)] (sig (bv 16))) body]
    , progCertificate = testCertificate "Mac.mac_correct"
    }
  where
    pairTy = TProd [bv 8, bv 8]
    body =
      ELam [("x", sig (bv 8)), ("y", sig (bv 8))] $
        EApp
          (prim (SigMealy (VBV 16 0)) [stepTy, sig pairTy] (sig (bv 16)))
          [ step
          , EApp
              (prim (SigLift 2) [tFuns [bv 8, bv 8] pairTy, sig (bv 8), sig (bv 8)] (sig pairTy))
              [ELam [("a", bv 8), ("b", bv 8)] (ETuple [v "a", v "b"]), v "x", v "y"]
          ]
    stepTy = tFuns [bv 16, pairTy] (TProd [bv 16, bv 16])
    zext16 e = EApp (prim (BvZext 16) [bv 8] (bv 16)) [e]
    step =
      ELam [("acc", bv 16), ("p", pairTy)] $
        ELet
          False
          [ Bind "acc'" (bv 16) $
              EApp
                (prim BvAdd [bv 16, bv 16] (bv 16))
                [ v "acc"
                , EApp (prim BvMul [bv 16, bv 16] (bv 16)) [zext16 (EProj 0 (v "p")), zext16 (EProj 1 (v "p"))]
                ]
          ]
          (ETuple [v "acc'", v "acc"])

macNormal :: NModule
macNormal =
  NModule
    { nmName = "mac"
    , nmDomain = sysDomain
    , nmInputs = [("x", bv 8), ("y", bv 8)]
    , nmOutputs = [NOutput "acc" (bv 16) (AVar "acc_q")]
    , nmBinds =
        [ NBind "acc_q" (bv 16) (NReg (VBV 16 0) (AVar "sum"))
        , NBind "xz" (bv 16) (NPrim (BvZext 16) [AVar "x"])
        , NBind "yz" (bv 16) (NPrim (BvZext 16) [AVar "y"])
        , NBind "prod" (bv 16) (NPrim BvMul [AVar "xz", AVar "yz"])
        , NBind "sum" (bv 16) (NPrim BvAdd [AVar "acc_q", AVar "prod"])
        ]
    , nmCertificate = testCertificate "Mac.mac_correct"
    }

macNetlist :: Module
macNetlist =
  Module
    { modName = Ident "mac"
    , modHeader = ["generated by gin test fixtures", "theorem: Mac.mac_correct"]
    , modClock = Ident "clk"
    , modReset = Ident "rst"
    , modInputs = [Net (Ident "x") (HVec 8), Net (Ident "y") (HVec 8)]
    , modOutputs = [Output (Net (Ident "acc") (HVec 16)) (ORef (Ident "acc_q"))]
    , modDecls =
        [ DReg (Net (Ident "acc_q") (HVec 16)) (HLitVec 16 0) (ORef (Ident "sum"))
        , DAssign (Net (Ident "xz") (HVec 16)) (HZext 16 (ORef (Ident "x")))
        , DAssign (Net (Ident "yz") (HVec 16)) (HZext 16 (ORef (Ident "y")))
        , DAssign (Net (Ident "prod") (HVec 16)) (HBin BMul (ORef (Ident "xz")) (ORef (Ident "yz")))
        , DAssign (Net (Ident "sum") (HVec 16)) (HBin BAdd (ORef (Ident "acc_q")) (ORef (Ident "prod")))
        ]
    }

-- | Includes a wrap-around at cycle 4: (65067 + 65025) mod 2^16 = 64556.
macVectors :: Vectors
macVectors =
  Vectors
    { vecTop = "mac"
    , vecInputs = [Port "x" (bv 8), Port "y" (bv 8)]
    , vecOutputs = [Port "acc" (bv 16)]
    , vecCycles =
        [ Cycle [VBV 8 3, VBV 8 4] [VBV 16 0]
        , Cycle [VBV 8 5, VBV 8 6] [VBV 16 12]
        , Cycle [VBV 8 255, VBV 8 255] [VBV 16 42]
        , Cycle [VBV 8 255, VBV 8 255] [VBV 16 65067]
        , Cycle [VBV 8 0, VBV 8 0] [VBV 16 64556]
        ]
    }

----------------------------------------------------------------------
-- detector

-- > detector b = mealy step 0 b where
-- >   step s i | s == 0    = (if i then 1 else 0, false)
-- >            | s == 1    = (if i then 1 else 2, false)
-- >            | otherwise = (if i then 1 else 0, i)
detectorProgram :: Program
detectorProgram =
  Program
    { progProducer = producer
    , progTop =
        TopEntity
          { topName = "detector"
          , topDomain = sysDomain
          , topInputs = [Port "b" TBool]
          , topOutputs = [Port "hit" TBool]
          , topDef = "Detector.detector"
          }
    , progDefs =
        [ Def "Detector.step" stepTy step
        , Def "Detector.detector" (TFun (sig TBool) (sig TBool)) body
        ]
    , progCertificate = testCertificate "Detector.detector_correct"
    }
  where
    stepTy = tFuns [bv 2, TBool] (TProd [bv 2, TBool])
    body =
      ELam [("b", sig TBool)] $
        EApp
          (prim (SigMealy (VBV 2 0)) [stepTy, sig TBool] (sig TBool))
          [EGlobal "Detector.step", v "b"]
    lit2 = ELit . VBV 2
    isState n = EApp (prim BvEq [bv 2, bv 2] TBool) [v "s", lit2 n]
    pick a b = EIf (v "i") (lit2 a) (lit2 b)
    step =
      ELam [("s", bv 2), ("i", TBool)] $
        EIf
          (isState 0)
          (ETuple [pick 1 0, ELit (VBool False)])
          ( EIf
              (isState 1)
              (ETuple [pick 1 2, ELit (VBool False)])
              (ETuple [pick 1 0, v "i"])
          )

-- | One mux per scalar component of the step function's result.
detectorNormal :: NModule
detectorNormal =
  NModule
    { nmName = "detector"
    , nmDomain = sysDomain
    , nmInputs = [("b", TBool)]
    , nmOutputs = [NOutput "hit" TBool (AVar "o_hit")]
    , nmBinds =
        [ NBind "s" (bv 2) (NReg (VBV 2 0) (AVar "s_next"))
        , NBind "is0" TBool (NPrim BvEq [AVar "s", ALit (VBV 2 0)])
        , NBind "is1" TBool (NPrim BvEq [AVar "s", ALit (VBV 2 1)])
        , NBind "pick10" (bv 2) (NMux (AVar "b") (ALit (VBV 2 1)) (ALit (VBV 2 0)))
        , NBind "pick12" (bv 2) (NMux (AVar "b") (ALit (VBV 2 1)) (ALit (VBV 2 2)))
        , NBind "s_inner" (bv 2) (NMux (AVar "is1") (AVar "pick12") (AVar "pick10"))
        , NBind "s_next" (bv 2) (NMux (AVar "is0") (AVar "pick10") (AVar "s_inner"))
        , NBind "hit_inner" TBool (NMux (AVar "is1") (ALit (VBool False)) (AVar "b"))
        , NBind "o_hit" TBool (NMux (AVar "is0") (ALit (VBool False)) (AVar "hit_inner"))
        ]
    , nmCertificate = testCertificate "Detector.detector_correct"
    }

detectorNetlist :: Module
detectorNetlist =
  Module
    { modName = Ident "detector"
    , modHeader = ["generated by gin test fixtures", "theorem: Detector.detector_correct"]
    , modClock = Ident "clk"
    , modReset = Ident "rst"
    , modInputs = [Net (Ident "b") HBit]
    , modOutputs = [Output (Net (Ident "hit") HBit) (ORef (Ident "o_hit"))]
    , modDecls =
        [ DReg (vec2 "s") (HLitVec 2 0) (ORef (Ident "s_next"))
        , DAssign (bit "is0") (HBin BEq (ORef (Ident "s")) (OConst (HLitVec 2 0)))
        , DAssign (bit "is1") (HBin BEq (ORef (Ident "s")) (OConst (HLitVec 2 1)))
        , DAssign (vec2 "pick10") (HMux (ORef (Ident "b")) (OConst (HLitVec 2 1)) (OConst (HLitVec 2 0)))
        , DAssign (vec2 "pick12") (HMux (ORef (Ident "b")) (OConst (HLitVec 2 1)) (OConst (HLitVec 2 2)))
        , DAssign (vec2 "s_inner") (HMux (ORef (Ident "is1")) (ORef (Ident "pick12")) (ORef (Ident "pick10")))
        , DAssign (vec2 "s_next") (HMux (ORef (Ident "is0")) (ORef (Ident "pick10")) (ORef (Ident "s_inner")))
        , DAssign (bit "hit_inner") (HMux (ORef (Ident "is1")) (OConst (HLitBit False)) (ORef (Ident "b")))
        , DAssign (bit "o_hit") (HMux (ORef (Ident "is0")) (OConst (HLitBit False)) (ORef (Ident "hit_inner")))
        ]
    }
  where
    vec2 n = Net (Ident n) (HVec 2)
    bit n = Net (Ident n) HBit

-- | b = 1 0 1 0 1 1 0 1; hit = 0 0 1 0 1 0 0 1 (overlapping matches).
detectorVectors :: Vectors
detectorVectors =
  Vectors
    { vecTop = "detector"
    , vecInputs = [Port "b" TBool]
    , vecOutputs = [Port "hit" TBool]
    , vecCycles =
        zipWith
          (\i o -> Cycle [VBool i] [VBool o])
          [True, False, True, False, True, True, False, True]
          [False, False, True, False, True, False, False, True]
    }
